package alien.servlets;                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
import lazyj.page.BasePage;                                                                                                                                                                                                                                                    
import lazyj.ExtProperties;                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                               
import java.io.OutputStream;                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                               
public class Page extends BasePage {                                                                                                                                                                                                                                           
        private static ExtProperties globalProp = null;                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                               
        private static String sResDir = "";                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                               
        static{                                                                                                                                                                                                                                                                
                globalProp = new ExtProperties("config","page");                                                                                                                                                                                    
        }                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                               
        protected String getResDir(){                                                                                                                                                                                                                                          
                return globalProp.gets("base.res.dir");                                                                                                                                                                                                                        
        }                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                               
        public Page(final String sFile){                                                                                                                                                                                                                                       
                this(null, sFile, false);                                                                                                                                                                                                                                      
        }                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                               
        public Page(final String sFile, final boolean bCache){                                                                                                                                                                                                                 
                this(null, sFile, bCache);                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                               
        public Page(final OutputStream os, final String sFile){                                                                                                                                                                                                                
                this(os, sFile, false);                                                                                                                                                                                                                                        
        }                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                               
        public Page(final OutputStream os, final String sFile, final boolean bCache){                                                                                                                                                                                          
                super(os, sFile, bCache);                                                                                                                                                                                                                                      
        }                                                                                                                                                                                                                                                                      
}                                                                                                                                                                                                                                                                              
                   