#!/bin/bash

if [ "$1" == "setup" ]; then
    cd `dirname $0`

    mkdir -p ${HOME}/.j/config

    cp config/logging.properties config/config.properties ${HOME}/.j/config/

    mkdir -p ${HOME}/.j/trusts

    wget -q "https://cafiles.cern.ch/cafiles/certificates/CERN%20Certification%20Authority.crt" -O ${HOME}/.j/trusts/CERN_CA.der
    wget -q "https://cafiles.cern.ch/cafiles/certificates/CERN%20Root%20Certification%20Authority%202.crt" -O ${HOME}/.j/trusts/CERN_ROOT_CA2.der
    wget -q "https://cafiles.cern.ch/cafiles/certificates/CERN%20Grid%20Certification%20Authority.crt" -O ${HOME}/.j/trusts/CERN_Grid_CA.der

    chmod 400 ${HOME}/.globus/userkey.pem
    chmod 440 ${HOME}/.globus/usercert.pem

    exit 0
fi

if [ -z "$JALIEN_HOME" ]; then
    JALIEN_HOME=`pwd`
    export JALIEN_HOME
fi

CONFIG_DIR=${JALIEN_CONFIG_DIR:-${HOME}/.j/config}

if [ ! -d "$CONFIG_DIR" ]; then
    CONFIG_DIR="$JALIEN_HOME"/config
fi

if [ "$1" == "login" ]; then
    cd $JALIEN_HOME
    ./run.sh -DAliEnConfig=${CONFIG_DIR} alien.JBox $@
elif [ "$1" == "JobAgent" ]; then
    cd $JALIEN_HOME
    #./run.sh -Djavax.net.debug=ssl -DAliEnConfig=${CONFIG_DIR} -Djava.net.preferIPv4Stack=true alien.site.JobAgent
    #./run.sh  -DAliEnConfig=${CONFIG_DIR} -Djava.net.preferIPv4Stack=true alien.site.JobAgent
    $JALIEN_HOME/run.sh  -DAliEnConfig=${CONFIG_DIR} -Djava.net.preferIPv4Stack=true alien.site.JobAgent
elif [ "$1" == "ComputingElement" ]; then
    cd $JALIEN_HOME
    $JALIEN_HOME/run.sh  -DAliEnConfig=${CONFIG_DIR} -Djava.net.preferIPv4Stack=true alien.site.ComputingElement
elif [ "$1" == "TitanJobService" ]; then
    cd $JALIEN_HOME
    #./run.sh -Djavax.net.debug=ssl -DAliEnConfig=${CONFIG_DIR} -Djava.net.preferIPv4Stack=true alien.site.JobAgent
    #./run.sh  -DAliEnConfig=${CONFIG_DIR} -Djava.net.preferIPv4Stack=true alien.site.JobAgent
    $JALIEN_HOME/run.sh  -DAliEnConfig=${CONFIG_DIR} -Djava.net.preferIPv4Stack=true alien.site.TitanJobService
elif [ "$1" == "ArchiveMemberDelete" ]; then
    cd $JALIEN_HOME
    $JALIEN_HOME/run.sh  -DAliEnConfig=${CONFIG_DIR} -Djava.net.preferIPv4Stack=true alien.ArchiveMemberDelete $@
else
    cd $JALIEN_HOME
    ./run.sh -DAliEnConfig=${CONFIG_DIR} alien.JSh $@
fi
