#!/bin/bash

if [ "$1" == "login" ]; then


        cd $JALIEN_HOME
        ./run.sh -DAliEnConfig=${HOME}/.j/config alien.JBox $@

else 


	cd $JALIEN_HOME
	./run.sh -DAliEnConfig=${HOME}/.j/config alien.JSh $@


fi




