package alien.io.protocols;

public enum SourceExceptionCode {
    LOCAL_FILE_ALREADY_EXISTS,
    XRDCP_NOT_FOUND_IN_PATH,
    XRDFS_CANNOT_CONFIRM_UPLOAD,
    CANNOT_START_PROCESS,
    INTERRUPTED_WHILE_WAITING_FOR_COMMAND,
    XROOTD_TIMED_OUT,
    XROOTD_EXITED_WITH_CODE,
    LOCAL_FILE_SIZE_DIFFERENT,
    LOCAL_FILE_CANNOT_BE_CREATED,
    NO_SERVERS_HAVE_THE_FILE,
    NO_SUCH_FILE_OR_DIRECTORY,
    MD5_CHECKSUMS_DIFFER,
    SE_DOES_NOT_EXIST,
    TORRENT_GET_NOT_IMPLEMENTED,
    INTERNAL_ERROR
}
